MODEL:
  NUM_CLASSES: 4
  BACKBONE:
    NAME: 'deit_tiny_distilled_patch16_224'
    OUT_CHANNELS: (192,192, 512, 512, 512, 512)
    FEATURE_MAPS: [64,32, 16, 8, 4, 2]
    UPSAMPLE: "Conv"
  HEAD:
    NAME: 'SSDBoxHead'
  PRIORS:
    STRIDES: [8, 16, 32, 64, 100, 300]
    MIN_SIZES: [20.48, 51.2, 133.12, 215.04, 296.96, 378.88]
    MAX_SIZES: [51.2, 133.12, 215.04, 296.96, 378.88, 460.8]
    ASPECT_RATIOS: [[2], [2, 3], [2, 3], [2, 3], [2], [2]]
    BOXES_PER_LOCATION: [4,6,6,6,4,4]
INPUT:
  IMAGE_SIZE: 512
  STANDARDIZATION_MEAN: (0.17, 0.16, 0.17)
  STANDARDIZATION_STDEV: (0.08, 0.11, 0.08)
DATASETS:
  TRAIN: ("kaist_thermal_coco_train_set05", )
  TEST: ("kaist_rgb_coco_test_set611", "kaist_thermal_coco_test_set611","kaist_rgb_coco_test_day", "kaist_rgb_coco_test_night")
SCHEDULER:
  TYPE : 'Transformer'
SOLVER:
  NAME : "Transformer"
  LR: 5e-4
  MAX_ITER: None
  MAX_EPOCHS: 120
  BATCH_SIZE: 8
  WEIGHT_DECAY : 0.0
KD:
  ENABLE: True
  ENABLE_DML: True
  DISTILL_TYPE: ['L2']
  LOSS_WEIGHTS: {'l2':4.0}

OUTPUT_DIR: '/outputs/deit_tiny_ssd_kaist_st_1l2_wt_std'
