from yacs.config import CfgNode as CN

_C = CN(new_allowed=True)

_C.MODEL = CN(new_allowed=True)
_C.MODEL.BASE_CH = 1024
_C.MODEL.CLASS_AGNOSTIC = False
_C.MODEL.BBOX_NORMALIZE_TARGETS = True
_C.MODEL.BBOX_NORMALIZE_TARGETS_PRECOMPUTED = True
_C.MODEL.BBOX_NORMALIZE_MEANS = (0.0, 0.0, 0.0, 0.0)
_C.MODEL.BBOX_NORMALIZE_STDS = (0.1, 0.1, 0.2, 0.2)
_C.MODEL.POOLING_SIZE = 7
_C.MODEL.ANCHOR_SCALES = [2, 4, 8, 16, 32]
_C.MODEL.ANCHOR_RATIOS = [0.5, 0.75, 1, 1.33, 2]
_C.MODEL.FEAT_STRIDE = [16, ]
_C.MODEL.BBOX_INSIDE_WEIGHTS = (1.0, 1.0, 1.0, 1.0)

_C.MODEL.CEM_DOUT = 245
_C.MODEL.RPN_DOUT = 256
_C.MODEL.SAM_DOUT = 245
_C.MODEL.FC_DIM = 1024

_C.MODEL.RPN_POSITIVE_OVERLAP = 0.7
_C.MODEL.RPN_NEGATIVE_OVERLAP = 0.3
_C.MODEL.RPN_CLOBBER_POSITIVES = False
_C.MODEL.RPN_FG_FRACTION = 0.5
_C.MODEL.RPN_BATCHSIZE = 256
_C.MODEL.RPN_BBOX_INSIDE_WEIGHTS = (
    1.0, 1.0, 1.0, 1.0)
_C.MODEL.RPN_POSITIVE_WEIGHT = -1.0

_C.INPUT = CN(new_allowed=True)
_C.INPUT.SCALES = [240, 320, 480]

_C.CONFIG = CN(new_allowed=True)
_C.CONFIG.TRAIN = CN(new_allowed=True)
_C.CONFIG.TRAIN.NMS_METHOD = 2  # 0: binary 1: linear 2: gaussian
_C.CONFIG.TEST = CN(new_allowed=True)
_C.CONFIG.TEST.BBOX_REG = True
_C.CONFIG.TEST.NMS = 0.3
_C.CONFIG.TEST.MAX_PER_IMAGE = 100
_C.CONFIG.TEST.NMS_METHOD = 2  # 0: binary 1: linear 2: gaussian

_C.TRAIN = CN(new_allowed=True)
_C.TRAIN.BATCH_SIZE = 128
_C.TRAIN.FG_FRACTION = 0.25
_C.TRAIN.FG_THRESH = 0.5
_C.TRAIN.BG_THRESH_HI = 0.5
_C.TRAIN.BG_THRESH_LO = 0.0
_C.TRAIN.RPN_NMS_THRESH = 0.7
_C.TRAIN.RPN_PRE_NMS_TOP_N = 12000
_C.TRAIN.RPN_POST_NMS_TOP_N = 2000

_C.TEST = CN(new_allowed=True)
_C.TEST.RPN_NMS_THRESH = 0.7
_C.TEST.RPN_PRE_NMS_TOP_N = 6000
_C.TEST.RPN_POST_NMS_TOP_N = 1000

_C.LOGGER = CN(new_allowed=True)
_C.LOGGER.NAME = "ThunderNet"
